### ISSUE TITLE
I can't use it 

### ISSUE THREAD

**Issue by git-duzhengjie** [latelierco/vue-signalr#8]
I have installed it ,but when i run serve,it tips:"This dependency was not found:

* vue-signalr in ./src/main.js

To install it, you can run: npm install --save vue-signalr"

**Comment by romzrarugal** [comment]
Import it like this

**import VueSignalR from '@latelier/vue-signalr'**

**Comment by git-duzhengjie** [comment]
> Import it like this
> 
> **import VueSignalR from '@latelier/vue-signalr'**

i solved it by this
import SignalR from '@latelier/vue-signalr'
